### ISSUE TITLE
Plugin dependencies

### ISSUE THREAD

**Issue by SinaCutie** [matthewgraybosch/oedipus-pelican-starter#1]
In order to `make html` I also had to install `Image`, `bs4`, `pysvg-py3`, and `cssutils` via pip to satisfy dependencies for `better_figures_and_images`.

Should this be listed in README?

**Comment by matthewgraybosch** [comment]
@SinaCutie, I've updated the README. I hope it's clearer for you and everybody else. Thanks for raising this issue.
